version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
   # networks:
    #  - app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app
    tty: true
    ports:
      - 80:8080
#    networks:
#      - app
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
volumes:
  redis:
    driver: local
#networks:
#  app: